/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (ridgeracertype4)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: (group, sub) -> R4.BIN entry index; group 0 = 0x292+sub (overlays are entries 659-672) */
#define PSX_FN_R4Bin_EntryIndex 0x80012234u
#define func_80012234 R4Bin_EntryIndex  /* alias */

/* guessed: CdSearchFile \R4.BIN;1, reads its 934-entry sector table, builds {CdlLOC,count} at 0x80109658 */
#define PSX_FN_R4Bin_Init 0x80012288u
#define func_80012288 R4Bin_Init  /* alias */

/* guessed: (index, dest) starts an async sector read of one R4.BIN entry */
#define PSX_FN_R4Bin_ReadAsync 0x80012924u
#define func_80012924 R4Bin_ReadAsync  /* alias */

/* guessed: polls the R4Bin_ReadAsync transfer for completion */
#define PSX_FN_R4Bin_ReadPoll 0x80012A50u
#define func_80012A50 R4Bin_ReadPoll  /* alias */

/* guessed: called by the CRT after InitHeap(0x801149AC, 0xE3658); calls SetMem(2) */
#define PSX_FN_R4_Main 0x8001E67Cu
#define func_8001E67C R4_Main  /* alias */

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8007D8F4u
#define func_8007D8F4 BootEntry  /* alias */
