/* r4_interp_fields.h - GENERATED by tools/gen_r4_interp_fields.py from
 * tools/data/r4_interp_fields.json. Do not edit; edit the JSON and rerun.
 *
 * Car and camera values R4 (SLUS-00797) draws from, interpolated between two
 * 30 Hz race ticks. The field list was first found by dogewow2048 in the
 * Japanese '60 FPS' cheat and re-derived for the US EXE (src = cheat). */
#ifndef R4_INTERP_FIELDS_H
#define R4_INTERP_FIELDS_H

#include <stdint.h>

enum { R4_FIELD_LINEAR = 0, R4_FIELD_ANGLE12 = 1, R4_FIELD_ANGLE12_H = 2 };
/* BODY fields snap together (a car, a camera); SELF fields snap alone. */
enum { R4_GROUP_BODY = 0, R4_GROUP_SELF = 1 };

typedef struct R4InterpField {
    uint16_t off;     /* byte offset from the object base */
    uint8_t  kind;    /* R4_FIELD_* */
    uint8_t  group;   /* R4_GROUP_* */
    uint32_t snap;    /* per-tick |delta| above which the value snaps */
} R4InterpField;

/* P1, P2 and eight opponents, stride 0x320. */
#define R4_INTERP_CAR_COUNT 10u
static const uint32_t R4_INTERP_CAR_BASES[R4_INTERP_CAR_COUNT] = {
    0x800AC0B0u, 0x800AC3D0u, 0x80107348u, 0x80107668u, 0x80107988u, 0x80107CA8u, 0x80107FC8u, 0x801082E8u, 0x80108608u, 0x80108928u
};
#define R4_INTERP_CAR_FIELD_COUNT 21u
static const R4InterpField R4_INTERP_CAR_FIELDS[R4_INTERP_CAR_FIELD_COUNT] = {
    { 0x000u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x40000u },  /* fine X (pos<<8) [cheat] */
    { 0x008u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x40000u },  /* fine Z (pos<<8) [cheat] */
    { 0x010u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* world X [cheat+draw] */
    { 0x014u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* world Y [cheat+draw] */
    { 0x018u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* world Z [cheat+draw] */
    { 0x070u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* body/render X (+0x60) [cheat+draw] */
    { 0x074u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* body/render Y (+0x64) [cheat+draw] */
    { 0x078u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* body/render Z (+0x68) [cheat+draw] */
    { 0x0C8u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* vector copied to sp+0x168 by car draw [I] [cheat+draw] */
    { 0x0CCu, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* idem [cheat+draw] */
    { 0x0D0u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* idem [cheat+draw] */
    { 0x050u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* pitch (RotX(-x), RotX(0x1A8-x)) [cheat+draw] */
    { 0x054u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* yaw (RotY(-x)) [cheat+draw] */
    { 0x058u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* roll (RotZ(-x), RotZ(0x1AA-x)) [cheat+draw] */
    { 0x060u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x400u },  /* body offset X added to +0x70/+0x10 [draw] */
    { 0x064u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x400u },  /* body offset Y [draw] */
    { 0x068u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x400u },  /* body offset Z [draw] */
    { 0x1A8u, R4_FIELD_ANGLE12_H, R4_GROUP_BODY, 0x200u },  /* s16 pitch add [draw] */
    { 0x1AAu, R4_FIELD_ANGLE12_H, R4_GROUP_BODY, 0x200u },  /* s16 roll add [draw] */
    { 0x080u, R4_FIELD_ANGLE12_H, R4_GROUP_SELF, 0x800u },  /* s16 wheel angle (RotX(-x)); snap at half turn [draw] */
    { 0x084u, R4_FIELD_ANGLE12_H, R4_GROUP_SELF, 0x200u },  /* s16 wheel angle (RotZ(-x)) [draw] */
};

/* Scratchpad camera read by the camera builder 0x8006E4D0 (modes 1, 2, 4, 5). */
#define R4_INTERP_CAMERA_BASE 0x1F800000u
#define R4_INTERP_CAMERA_FIELD_COUNT 6u
static const R4InterpField R4_INTERP_CAMERA_FIELDS[R4_INTERP_CAMERA_FIELD_COUNT] = {
    { 0x008u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* camera X [cheat] */
    { 0x00Cu, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* camera Y [cheat] */
    { 0x010u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* camera Z [cheat] */
    { 0x018u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* RotX input of 0x8006E4D0 [cheat] */
    { 0x01Cu, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* RotY input [cheat] */
    { 0x020u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* RotZ input [cheat] */
};

/* 2P split screen (mode 3): overlay-661 per-player camera blocks, copied
 * four words at a time into scratch 1F800018 (angles) / 1F800008 (position). */
static const uint32_t R4_INTERP_2P_ANGLE_BLOCKS[2] = { 0x80118500u, 0x80118510u };
static const uint32_t R4_INTERP_2P_POS_BLOCKS[2] = { 0x80118520u, 0x80118530u };
#define R4_INTERP_2P_FIELD_COUNT 3u
static const R4InterpField R4_INTERP_2P_ANGLE_FIELDS[R4_INTERP_2P_FIELD_COUNT] = {
    { 0x000u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* RotX input (-> 1F800018) [cheat] */
    { 0x004u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* RotY input (-> 1F80001C) [cheat] */
    { 0x008u, R4_FIELD_ANGLE12, R4_GROUP_BODY, 0x200u },  /* RotZ input (-> 1F800020) [cheat] */
};
static const R4InterpField R4_INTERP_2P_POS_FIELDS[R4_INTERP_2P_FIELD_COUNT] = {
    { 0x000u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* camera X (-> 1F800008) [cheat] */
    { 0x004u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* camera Y (-> 1F80000C) [cheat] */
    { 0x008u, R4_FIELD_LINEAR, R4_GROUP_BODY, 0x1000u },  /* camera Z (-> 1F800010) [cheat] */
};

#endif
