#!/usr/bin/env python3
"""gen_r4_interp_fields.py - generate src/mods/r4_interp_fields.h.

The R4 Frame Rate package interpolates a fixed set of car and camera values
between two 30 Hz race ticks (src/mods/r4_interp.c). That set lives in
tools/data/r4_interp_fields.json; this script turns it into C tables so the
plugin and its unit test share one source of truth.

The field list was first worked out for the Japanese release by dogewow2048
(the "60 FPS" cheat) and re-derived for the US EXE; entries marked
src = "cheat" carry that credit.

Usage:
  python3 tools/gen_r4_interp_fields.py            # write the header
  python3 tools/gen_r4_interp_fields.py --check    # fail if it is stale
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tools", "data", "r4_interp_fields.json")
OUT = os.path.join(ROOT, "src", "mods", "r4_interp_fields.h")

KINDS = {"linear": "R4_FIELD_LINEAR", "angle12": "R4_FIELD_ANGLE12",
         "angle12_h": "R4_FIELD_ANGLE12_H"}
GROUPS = {"body": "R4_GROUP_BODY", "self": "R4_GROUP_SELF"}


def hexint(v):
    return int(v, 16) if isinstance(v, str) else int(v)


def field_rows(fields):
    rows = []
    for f in fields:
        if f.get("enabled", True) is False:
            continue
        kind = KINDS[f["kind"]]
        group = GROUPS[f.get("group", "body")]
        what = f.get("what", "").replace("*/", "* /")
        rows.append("    { 0x%03Xu, %s, %s, 0x%Xu },  /* %s [%s] */" % (
            hexint(f["off"]), kind, group, hexint(f["snap"]), what,
            f.get("src", "")))
    return rows


def render(d):
    cars = d["cars"]
    cam = d["camera_scratch"]
    c2p = d["camera_2p"]
    out = []
    out.append("/* r4_interp_fields.h - GENERATED by tools/gen_r4_interp_fields.py from")
    out.append(" * tools/data/r4_interp_fields.json. Do not edit; edit the JSON and rerun.")
    out.append(" *")
    out.append(" * Car and camera values R4 (SLUS-00797) draws from, interpolated between two")
    out.append(" * 30 Hz race ticks. The field list was first found by dogewow2048 in the")
    out.append(" * Japanese '60 FPS' cheat and re-derived for the US EXE (src = cheat). */")
    out.append("#ifndef R4_INTERP_FIELDS_H")
    out.append("#define R4_INTERP_FIELDS_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("enum { R4_FIELD_LINEAR = 0, R4_FIELD_ANGLE12 = 1, R4_FIELD_ANGLE12_H = 2 };")
    out.append("/* BODY fields snap together (a car, a camera); SELF fields snap alone. */")
    out.append("enum { R4_GROUP_BODY = 0, R4_GROUP_SELF = 1 };")
    out.append("")
    out.append("typedef struct R4InterpField {")
    out.append("    uint16_t off;     /* byte offset from the object base */")
    out.append("    uint8_t  kind;    /* R4_FIELD_* */")
    out.append("    uint8_t  group;   /* R4_GROUP_* */")
    out.append("    uint32_t snap;    /* per-tick |delta| above which the value snaps */")
    out.append("} R4InterpField;")
    out.append("")
    bases = [hexint(b) for b in cars["bases"]]
    out.append("/* P1, P2 and eight opponents, stride 0x320. */")
    out.append("#define R4_INTERP_CAR_COUNT %du" % len(bases))
    out.append("static const uint32_t R4_INTERP_CAR_BASES[R4_INTERP_CAR_COUNT] = {")
    out.append("    " + ", ".join("0x%08Xu" % b for b in bases))
    out.append("};")
    rows = field_rows(cars["fields"]) + field_rows(cars.get("optional", []))
    out.append("#define R4_INTERP_CAR_FIELD_COUNT %du" % len(rows))
    out.append("static const R4InterpField R4_INTERP_CAR_FIELDS[R4_INTERP_CAR_FIELD_COUNT] = {")
    out.extend(rows)
    out.append("};")
    out.append("")
    rows = field_rows(cam["fields"])
    out.append("/* Scratchpad camera read by the camera builder 0x8006E4D0 (modes %s). */" %
               ", ".join(str(m) for m in cam["modes"]))
    out.append("#define R4_INTERP_CAMERA_BASE 0x%08Xu" % hexint(cam["base"]))
    out.append("#define R4_INTERP_CAMERA_FIELD_COUNT %du" % len(rows))
    out.append("static const R4InterpField R4_INTERP_CAMERA_FIELDS[R4_INTERP_CAMERA_FIELD_COUNT] = {")
    out.extend(rows)
    out.append("};")
    out.append("")
    out.append("/* 2P split screen (mode 3): overlay-661 per-player camera blocks, copied")
    out.append(" * four words at a time into scratch 1F800018 (angles) / 1F800008 (position). */")
    ang = [hexint(b) for b in c2p["angle_blocks"]]
    pos = [hexint(b) for b in c2p["pos_blocks"]]
    out.append("static const uint32_t R4_INTERP_2P_ANGLE_BLOCKS[2] = { 0x%08Xu, 0x%08Xu };" % tuple(ang))
    out.append("static const uint32_t R4_INTERP_2P_POS_BLOCKS[2] = { 0x%08Xu, 0x%08Xu };" % tuple(pos))
    ra = field_rows([dict(f, group="body") for f in c2p["fields_angle"]])
    rp = field_rows([dict(f, group="body") for f in c2p["fields_pos"]])
    out.append("#define R4_INTERP_2P_FIELD_COUNT %du" % len(ra))
    out.append("static const R4InterpField R4_INTERP_2P_ANGLE_FIELDS[R4_INTERP_2P_FIELD_COUNT] = {")
    out.extend(ra)
    out.append("};")
    out.append("static const R4InterpField R4_INTERP_2P_POS_FIELDS[R4_INTERP_2P_FIELD_COUNT] = {")
    out.extend(rp)
    out.append("};")
    out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main():
    d = json.load(open(SRC))
    text = render(d)
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("%s is stale; run tools/gen_r4_interp_fields.py" % OUT)
            return 1
        print("r4_interp_fields.h is current")
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
